---
title: "\"Books in the Home\" Meta-Analysis"
author: "Vinay Tummarakota"
date: "2024-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(glue)
library(readxl)
library(tidyverse)
library(metafor)

source("helper_functions.R")
```

## Table of Contents: 
1. Convert Cohen's $d$ to Hedge's $g$
2. Estimate meta-analytic effect size
3. Examine publication bias
4. Conduct meta-regression

### Convert Cohen's $d$ to Hedge's $g$

```{r convert-to-hedges-g}
effect_sizes <- read_excel("coded_effect_sizes.xlsx")

cleaned_effect_sizes <- effect_sizes %>%
  mutate(j = 1 - 3 / (4*(sample_size_treatment + sample_size_control - 2) - 1)) %>%
  mutate(hedges_g = cohens_d * j, standard_error_g = standard_error_d * j) %>%
  select(-c(j))
```

### Estimate meta-analytic effect size

```{r ach-meta-analytic-effect-size}
ach_model <- estimate_meta_analytic_effect_size(cleaned_effect_sizes, outcome = "Reading Achievement", include_subpopulation = FALSE)
summary(ach_model)
forest(ach_model)
```

```{r orf-meta-analytic-effect-size}
orf_model <- estimate_meta_analytic_effect_size(cleaned_effect_sizes, outcome = "Oral Reading Fluency", include_subpopulation = FALSE)
summary(orf_model)
forest(orf_model)
```

### Examine publication bias 

```{r ach-publication-bias}
funnel(ach_model)
```

### Conduct meta-regression

```{r meta-regression}
# Anger et al (2024) is dropped from the meta-regression because it wasn't possible to quantify the length of the intervention in terms of the # of summers. 
ach_meta_reg <- conduct_meta_regression(cleaned_effect_sizes, outcome = "Reading Achievement", include_subpopulation = TRUE)

# due to multi-collinearity, the {is_matched_skill_level_books} variable is dropped
summary(ach_meta_reg)

regplot(ach_meta_reg, mod = "pop_percent_welfare_dependent", xlab= "% of Welfare-Dependent Students in Sample", ylab = "Effect Size (d)")
```

```{r bernies-book-bank-prediction}
inputs <- list(
  int_length_in_summers = 3, 
  int_scaffolded = FALSE, 
  int_self_selected_books = TRUE, 
  # assume low-income sample = 75% free/reduced-price lunch
  pop_percent_welfare_dependent = 0.75,
  # PAP says Spring 2019 achievement data on grade 1 and grade 3 students (averages to grade 2)
  pop_avg_grade_level_at_int_start = 2, 
  # seems like achievement is measured right when intervention ends? PAP isn't super clear on this
  out_num_months_since_int_end = 0
)

pred <- predict(ach_meta_reg, newmods = do.call(cbind, inputs))

print(glue("Based on the present meta-regression, Bernie's Book Bank will have an estimated impact between {round(pred$pi.lb, 2)}-{round(pred$pi.ub, 2)} SD with average predicted impact equal to {round(pred$pred, 2)} SD."))
```

```{r books-for-ownership-prediction}
inputs <- list(
  int_length_in_summers = 2, 
  int_scaffolded = TRUE, 
  int_self_selected_books = TRUE, 
  # assume low-income sample = 75% free/reduced-price lunch
  pop_percent_welfare_dependent = 0.75,
  # PAP says baseline survey will be administered in Fall of grade 2
  pop_avg_grade_level_at_int_start = 2, 
  # achievement is measured in Fall of grade 4 (i.e. right after second summer)
  out_num_months_since_int_end = 0
)

pred <- predict(ach_meta_reg, newmods = do.call(cbind, inputs))

print(glue("Based on the present meta-regression, Books For Ownership will have an estimated impact between {round(pred$pi.lb, 2)}-{round(pred$pi.ub, 2)} SD with average predicted impact equal to {round(pred$pred, 2)} SD."))
```
